# Generated by Django 3.2.8 on 2021-11-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prenom', models.CharField(max_length=50)),
                ('Nom', models.CharField(max_length=50)),
                ('Adresse_Rue', models.CharField(max_length=50)),
                ('Adresse_CP', models.CharField(max_length=50)),
                ('Adresse_Ville', models.CharField(max_length=50)),
                ('Telephone', models.CharField(max_length=10)),
                ('Mail', models.CharField(max_length=50)),
                ('Genre', models.CharField(max_length=50)),
                ('Niveau', models.CharField(max_length=20)),
                ('Numero_Licence', models.CharField(max_length=20)),
                ('Date_Naissance', models.DateTimeField()),
                ('Certificat_Medical', models.CharField(max_length=50)),
                ('Pointure', models.CharField(max_length=50)),
                ('Taille', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entraineur',
            fields=[
                ('adherent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='entraineur', serialize=False, to='adherents.adherent')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('adherents', models.ManyToManyField(to='adherents.Adherent')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('entraineur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='adherents.entraineur')),
            ],
        ),
        migrations.CreateModel(
            name='Entrainement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dates', models.DateTimeField()),
                ('Lien_fichier', models.CharField(max_length=300)),
                ('entraineurs', models.ManyToManyField(to='adherents.Entraineur')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachs_entrainement', to='adherents.coach')),
            ],
        ),
    ]
